<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DatabaseTools.DbTools\DatabaseTools.DbTools.csproj" />
        <ProjectReference Include="..\..\SystemTools\SystemTools.SystemToolsShared\SystemTools.SystemToolsShared.csproj" />
    </ItemGroup>

</Project>